/***************************************************************************
 *             __________               __   ___.
 *   Open      \______   \ ____   ____ |  | _\_ |__   _______  ___
 *   Source     |       _//  _ \_/ ___\|  |/ /| __ \ /  _ \  \/  /
 *   Jukebox    |    |   (  <_> )  \___|    < | \_\ (  <_> > <  <
 *   Firmware   |____|_  /\____/ \___  >__|_ \|___  /\____/__/\_ \
 *                     \/            \/     \/    \/            \/
 *
 * Copyright (C) 2026 Ricardo Gomez
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 ****************************************************************************/
/* F12: see metro_turnstile_table.c (GENERATED by
 * firmware/tools/gen_turnstile_table.py) for the full explanation.
 * metro_fb.c is the only consumer. */
#ifndef METRO_TURNSTILE_TABLE_H
#define METRO_TURNSTILE_TABLE_H

#include "lcd.h"

#define METRO_TURNSTILE_ANGLES     32
#define METRO_TURNSTILE_ANGLE_MIN  (-80)
#define METRO_TURNSTILE_ANGLE_MAX  50

/* Fixed point 8.8 -- metro_turnstile_step values are already scaled
 * by (1 << METRO_TURNSTILE_STEP_SHIFT). */
#define METRO_TURNSTILE_STEP_SHIFT 8

extern const short metro_turnstile_xs[METRO_TURNSTILE_ANGLES][LCD_WIDTH];
extern const unsigned short metro_turnstile_step[METRO_TURNSTILE_ANGLES][LCD_WIDTH];

#endif /* METRO_TURNSTILE_TABLE_H */
