/* GENERATED by design-system/generate.py --fonts -- do not edit by hand.
 *
 * moonlit (D-074): interseccion de los codepoints de
 * moonlit_translit.c que los SEIS roles con fuente de puntuacion
 * (todos salvo MFONT_DISPLAY) dibujan con un glifo real -- no solo
 * los que trae CUALQUIERA de los seis. Ver el comentario de
 * generate_fonts() en design-system/generate.py.
 */
#include "moonlit_punct_table.h"

const uint32_t moonlit_punct_codepoints[] = {
    0x2013,
    0x2014,
    0x2015,
    0x2018,
    0x2019,
    0x201A,
    0x201B,
    0x201C,
    0x201D,
    0x201E,
    0x201F,
    0x2022,
    0x2024,
    0x2025,
    0x2026,
    0x2032,
    0x2033,
    0x2039,
    0x203A,
    0x2122,
};

const int moonlit_punct_codepoint_count = 20;
