/* Generado por design-system/generate.py a partir de tokens.json. */
/* NO editar a mano: los cambios se perderian al regenerar. */
#ifndef MOONLIT_TOKENS_H
#define MOONLIT_TOKENS_H

/* LCD_RGBPACK depende del formato de pixel del target -- lo trae
 * "lcd.h" de Rockbox. Un test host que no enlaza Rockbox puede
 * definirlo antes de este include (solo necesita los *_RGB24). */
#ifndef LCD_RGBPACK
#define LCD_RGBPACK(r, g, b) (((r) << 16) | ((g) << 8) | (b))
#endif

#define MOONLIT_SCREEN_WIDTH  320
#define MOONLIT_SCREEN_HEIGHT 240
#define MOONLIT_SCREEN_DPI    160

/* Espaciados (px, grilla MD3) */
#define MOONLIT_SPACING_XS 4
#define MOONLIT_SPACING_SM 8
#define MOONLIT_SPACING_MD 16
#define MOONLIT_SPACING_LG 24
#define MOONLIT_SPACING_XL 32

/* Escala de forma: radios de esquina (px) */
#define MOONLIT_CORNER_NONE 0
#define MOONLIT_CORNER_XS 4
#define MOONLIT_CORNER_S 8
#define MOONLIT_CORNER_M 12
#define MOONLIT_CORNER_FULL 999

/* Elevacion tonal (D-012): deltas por canal aplicados a cada nivel
 * surface_container_<nivel> mas abajo -- ver EDGE_LIGHT/EDGE_SHADOW. */
#define MOONLIT_ELEVATION_LIGHT_EDGE_DELTA 12
#define MOONLIT_ELEVATION_SHADOW_EDGE_DELTA -10
#define MOONLIT_ELEVATION_EDGE_PX 1

/* Movimiento -- solo bajo lcd_active() (regla del repo) */
#define MOONLIT_MOTION_TRANSITION_MS 220
#define MOONLIT_MOTION_EASE "out_expo"
/* D-052 "Marea que sube" (C4) y "Filo de luna" (C3) */
#define MOONLIT_MOTION_SELECTION_MS 80
#define MOONLIT_MOTION_EASE_SELECTION "out_quad"
#define MOONLIT_MOTION_SEAM 1
/* D-067: marquesina de texto largo (maestro SS G) */
#define MOONLIT_MOTION_MARQUEE_STATIC_MS 2000
#define MOONLIT_MOTION_MARQUEE_SCROLL_MS 5000
#define MOONLIT_MOTION_MARQUEE_LOOP_GAP_PX 24

/* Esquema night -- 16 roles MD3 (D-028) */
#define MOONLIT_NIGHT_PRIMARY LCD_RGBPACK(169, 199, 232)
#define MOONLIT_NIGHT_PRIMARY_RGB24 0xA9C7E8
#define MOONLIT_NIGHT_ON_PRIMARY LCD_RGBPACK(11, 42, 68)
#define MOONLIT_NIGHT_ON_PRIMARY_RGB24 0x0B2A44
#define MOONLIT_NIGHT_PRIMARY_CONTAINER LCD_RGBPACK(31, 59, 87)
#define MOONLIT_NIGHT_PRIMARY_CONTAINER_RGB24 0x1F3B57
#define MOONLIT_NIGHT_ON_PRIMARY_CONTAINER LCD_RGBPACK(207, 227, 245)
#define MOONLIT_NIGHT_ON_PRIMARY_CONTAINER_RGB24 0xCFE3F5
#define MOONLIT_NIGHT_SURFACE LCD_RGBPACK(20, 22, 31)
#define MOONLIT_NIGHT_SURFACE_RGB24 0x14161F
#define MOONLIT_NIGHT_SURFACE_DIM LCD_RGBPACK(16, 18, 25)
#define MOONLIT_NIGHT_SURFACE_DIM_RGB24 0x101219
#define MOONLIT_NIGHT_SURFACE_BRIGHT LCD_RGBPACK(56, 61, 77)
#define MOONLIT_NIGHT_SURFACE_BRIGHT_RGB24 0x383D4D
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOWEST LCD_RGBPACK(11, 12, 18)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOWEST_RGB24 0x0B0C12
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOW LCD_RGBPACK(25, 28, 38)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOW_RGB24 0x191C26
#define MOONLIT_NIGHT_SURFACE_CONTAINER LCD_RGBPACK(30, 33, 44)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_RGB24 0x1E212C
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGH LCD_RGBPACK(38, 42, 55)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGH_RGB24 0x262A37
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGHEST LCD_RGBPACK(47, 51, 65)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGHEST_RGB24 0x2F3341
#define MOONLIT_NIGHT_ON_SURFACE LCD_RGBPACK(231, 229, 234)
#define MOONLIT_NIGHT_ON_SURFACE_RGB24 0xE7E5EA
#define MOONLIT_NIGHT_ON_SURFACE_VARIANT LCD_RGBPACK(184, 182, 192)
#define MOONLIT_NIGHT_ON_SURFACE_VARIANT_RGB24 0xB8B6C0
#define MOONLIT_NIGHT_OUTLINE LCD_RGBPACK(139, 137, 146)
#define MOONLIT_NIGHT_OUTLINE_RGB24 0x8B8992
#define MOONLIT_NIGHT_OUTLINE_VARIANT LCD_RGBPACK(62, 65, 80)
#define MOONLIT_NIGHT_OUTLINE_VARIANT_RGB24 0x3E4150

/* Esquema night -- bordes de elevacion (D-012): luz arriba-izquierda,
 * sombra abajo-derecha, precalculados por canal, cero costo por cuadro. */
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOWEST_EDGE_LIGHT LCD_RGBPACK(23, 24, 30)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOWEST_EDGE_LIGHT_RGB24 0x17181E
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOWEST_EDGE_SHADOW LCD_RGBPACK(1, 2, 8)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOWEST_EDGE_SHADOW_RGB24 0x010208
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOW_EDGE_LIGHT LCD_RGBPACK(37, 40, 50)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOW_EDGE_LIGHT_RGB24 0x252832
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOW_EDGE_SHADOW LCD_RGBPACK(15, 18, 28)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_LOW_EDGE_SHADOW_RGB24 0x0F121C
#define MOONLIT_NIGHT_SURFACE_CONTAINER_EDGE_LIGHT LCD_RGBPACK(42, 45, 56)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_EDGE_LIGHT_RGB24 0x2A2D38
#define MOONLIT_NIGHT_SURFACE_CONTAINER_EDGE_SHADOW LCD_RGBPACK(20, 23, 34)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_EDGE_SHADOW_RGB24 0x141722
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGH_EDGE_LIGHT LCD_RGBPACK(50, 54, 67)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGH_EDGE_LIGHT_RGB24 0x323643
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGH_EDGE_SHADOW LCD_RGBPACK(28, 32, 45)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGH_EDGE_SHADOW_RGB24 0x1C202D
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGHEST_EDGE_LIGHT LCD_RGBPACK(59, 63, 77)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGHEST_EDGE_LIGHT_RGB24 0x3B3F4D
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGHEST_EDGE_SHADOW LCD_RGBPACK(37, 41, 55)
#define MOONLIT_NIGHT_SURFACE_CONTAINER_HIGHEST_EDGE_SHADOW_RGB24 0x252937

/* Esquema dawn -- 16 roles MD3 (D-028) */
#define MOONLIT_DAWN_PRIMARY LCD_RGBPACK(62, 94, 125)
#define MOONLIT_DAWN_PRIMARY_RGB24 0x3E5E7D
#define MOONLIT_DAWN_ON_PRIMARY LCD_RGBPACK(255, 255, 255)
#define MOONLIT_DAWN_ON_PRIMARY_RGB24 0xFFFFFF
#define MOONLIT_DAWN_PRIMARY_CONTAINER LCD_RGBPACK(215, 230, 243)
#define MOONLIT_DAWN_PRIMARY_CONTAINER_RGB24 0xD7E6F3
#define MOONLIT_DAWN_ON_PRIMARY_CONTAINER LCD_RGBPACK(22, 50, 74)
#define MOONLIT_DAWN_ON_PRIMARY_CONTAINER_RGB24 0x16324A
#define MOONLIT_DAWN_SURFACE LCD_RGBPACK(245, 243, 249)
#define MOONLIT_DAWN_SURFACE_RGB24 0xF5F3F9
#define MOONLIT_DAWN_SURFACE_DIM LCD_RGBPACK(216, 214, 222)
#define MOONLIT_DAWN_SURFACE_DIM_RGB24 0xD8D6DE
#define MOONLIT_DAWN_SURFACE_BRIGHT LCD_RGBPACK(252, 250, 255)
#define MOONLIT_DAWN_SURFACE_BRIGHT_RGB24 0xFCFAFF
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOWEST LCD_RGBPACK(255, 255, 255)
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOWEST_RGB24 0xFFFFFF
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOW LCD_RGBPACK(239, 237, 244)
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOW_RGB24 0xEFEDF4
#define MOONLIT_DAWN_SURFACE_CONTAINER LCD_RGBPACK(233, 231, 239)
#define MOONLIT_DAWN_SURFACE_CONTAINER_RGB24 0xE9E7EF
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGH LCD_RGBPACK(227, 225, 233)
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGH_RGB24 0xE3E1E9
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGHEST LCD_RGBPACK(221, 219, 227)
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGHEST_RGB24 0xDDDBE3
#define MOONLIT_DAWN_ON_SURFACE LCD_RGBPACK(27, 27, 33)
#define MOONLIT_DAWN_ON_SURFACE_RGB24 0x1B1B21
#define MOONLIT_DAWN_ON_SURFACE_VARIANT LCD_RGBPACK(70, 69, 76)
#define MOONLIT_DAWN_ON_SURFACE_VARIANT_RGB24 0x46454C
#define MOONLIT_DAWN_OUTLINE LCD_RGBPACK(118, 118, 128)
#define MOONLIT_DAWN_OUTLINE_RGB24 0x767680
#define MOONLIT_DAWN_OUTLINE_VARIANT LCD_RGBPACK(198, 197, 207)
#define MOONLIT_DAWN_OUTLINE_VARIANT_RGB24 0xC6C5CF

/* Esquema dawn -- bordes de elevacion (D-012): luz arriba-izquierda,
 * sombra abajo-derecha, precalculados por canal, cero costo por cuadro. */
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOWEST_EDGE_LIGHT LCD_RGBPACK(255, 255, 255)
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOWEST_EDGE_LIGHT_RGB24 0xFFFFFF
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOWEST_EDGE_SHADOW LCD_RGBPACK(245, 245, 245)
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOWEST_EDGE_SHADOW_RGB24 0xF5F5F5
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOW_EDGE_LIGHT LCD_RGBPACK(251, 249, 255)
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOW_EDGE_LIGHT_RGB24 0xFBF9FF
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOW_EDGE_SHADOW LCD_RGBPACK(229, 227, 234)
#define MOONLIT_DAWN_SURFACE_CONTAINER_LOW_EDGE_SHADOW_RGB24 0xE5E3EA
#define MOONLIT_DAWN_SURFACE_CONTAINER_EDGE_LIGHT LCD_RGBPACK(245, 243, 251)
#define MOONLIT_DAWN_SURFACE_CONTAINER_EDGE_LIGHT_RGB24 0xF5F3FB
#define MOONLIT_DAWN_SURFACE_CONTAINER_EDGE_SHADOW LCD_RGBPACK(223, 221, 229)
#define MOONLIT_DAWN_SURFACE_CONTAINER_EDGE_SHADOW_RGB24 0xDFDDE5
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGH_EDGE_LIGHT LCD_RGBPACK(239, 237, 245)
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGH_EDGE_LIGHT_RGB24 0xEFEDF5
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGH_EDGE_SHADOW LCD_RGBPACK(217, 215, 223)
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGH_EDGE_SHADOW_RGB24 0xD9D7DF
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGHEST_EDGE_LIGHT LCD_RGBPACK(233, 231, 239)
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGHEST_EDGE_LIGHT_RGB24 0xE9E7EF
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGHEST_EDGE_SHADOW LCD_RGBPACK(211, 209, 217)
#define MOONLIT_DAWN_SURFACE_CONTAINER_HIGHEST_EDGE_SHADOW_RGB24 0xD3D1D9

/* Presets de acento (sustituyen enum metro_accent, D-028) */
#define MOONLIT_NIGHT_MOONSTONE_PRIMARY LCD_RGBPACK(169, 199, 232)
#define MOONLIT_NIGHT_MOONSTONE_PRIMARY_RGB24 0xA9C7E8
#define MOONLIT_NIGHT_MOONSTONE_ON_PRIMARY LCD_RGBPACK(11, 42, 68)
#define MOONLIT_NIGHT_MOONSTONE_ON_PRIMARY_RGB24 0x0B2A44
#define MOONLIT_NIGHT_MOONSTONE_PRIMARY_CONTAINER LCD_RGBPACK(31, 59, 87)
#define MOONLIT_NIGHT_MOONSTONE_PRIMARY_CONTAINER_RGB24 0x1F3B57
#define MOONLIT_NIGHT_MOONSTONE_ON_PRIMARY_CONTAINER LCD_RGBPACK(207, 227, 245)
#define MOONLIT_NIGHT_MOONSTONE_ON_PRIMARY_CONTAINER_RGB24 0xCFE3F5
#define MOONLIT_DAWN_MOONSTONE_PRIMARY LCD_RGBPACK(62, 94, 125)
#define MOONLIT_DAWN_MOONSTONE_PRIMARY_RGB24 0x3E5E7D
#define MOONLIT_DAWN_MOONSTONE_ON_PRIMARY LCD_RGBPACK(255, 255, 255)
#define MOONLIT_DAWN_MOONSTONE_ON_PRIMARY_RGB24 0xFFFFFF
#define MOONLIT_DAWN_MOONSTONE_PRIMARY_CONTAINER LCD_RGBPACK(215, 230, 243)
#define MOONLIT_DAWN_MOONSTONE_PRIMARY_CONTAINER_RGB24 0xD7E6F3
#define MOONLIT_DAWN_MOONSTONE_ON_PRIMARY_CONTAINER LCD_RGBPACK(22, 50, 74)
#define MOONLIT_DAWN_MOONSTONE_ON_PRIMARY_CONTAINER_RGB24 0x16324A
#define MOONLIT_NIGHT_TIDE_PRIMARY LCD_RGBPACK(143, 214, 199)
#define MOONLIT_NIGHT_TIDE_PRIMARY_RGB24 0x8FD6C7
#define MOONLIT_NIGHT_TIDE_ON_PRIMARY LCD_RGBPACK(6, 50, 41)
#define MOONLIT_NIGHT_TIDE_ON_PRIMARY_RGB24 0x063229
#define MOONLIT_NIGHT_TIDE_PRIMARY_CONTAINER LCD_RGBPACK(22, 72, 60)
#define MOONLIT_NIGHT_TIDE_PRIMARY_CONTAINER_RGB24 0x16483C
#define MOONLIT_NIGHT_TIDE_ON_PRIMARY_CONTAINER LCD_RGBPACK(195, 239, 228)
#define MOONLIT_NIGHT_TIDE_ON_PRIMARY_CONTAINER_RGB24 0xC3EFE4
#define MOONLIT_DAWN_TIDE_PRIMARY LCD_RGBPACK(44, 110, 93)
#define MOONLIT_DAWN_TIDE_PRIMARY_RGB24 0x2C6E5D
#define MOONLIT_DAWN_TIDE_ON_PRIMARY LCD_RGBPACK(255, 255, 255)
#define MOONLIT_DAWN_TIDE_ON_PRIMARY_RGB24 0xFFFFFF
#define MOONLIT_DAWN_TIDE_PRIMARY_CONTAINER LCD_RGBPACK(207, 239, 230)
#define MOONLIT_DAWN_TIDE_PRIMARY_CONTAINER_RGB24 0xCFEFE6
#define MOONLIT_DAWN_TIDE_ON_PRIMARY_CONTAINER LCD_RGBPACK(11, 50, 38)
#define MOONLIT_DAWN_TIDE_ON_PRIMARY_CONTAINER_RGB24 0x0B3226
#define MOONLIT_NIGHT_EMBER_PRIMARY LCD_RGBPACK(232, 185, 143)
#define MOONLIT_NIGHT_EMBER_PRIMARY_RGB24 0xE8B98F
#define MOONLIT_NIGHT_EMBER_ON_PRIMARY LCD_RGBPACK(68, 42, 11)
#define MOONLIT_NIGHT_EMBER_ON_PRIMARY_RGB24 0x442A0B
#define MOONLIT_NIGHT_EMBER_PRIMARY_CONTAINER LCD_RGBPACK(87, 58, 26)
#define MOONLIT_NIGHT_EMBER_PRIMARY_CONTAINER_RGB24 0x573A1A
#define MOONLIT_NIGHT_EMBER_ON_PRIMARY_CONTAINER LCD_RGBPACK(245, 220, 195)
#define MOONLIT_NIGHT_EMBER_ON_PRIMARY_CONTAINER_RGB24 0xF5DCC3
#define MOONLIT_DAWN_EMBER_PRIMARY LCD_RGBPACK(138, 90, 44)
#define MOONLIT_DAWN_EMBER_PRIMARY_RGB24 0x8A5A2C
#define MOONLIT_DAWN_EMBER_ON_PRIMARY LCD_RGBPACK(255, 255, 255)
#define MOONLIT_DAWN_EMBER_ON_PRIMARY_RGB24 0xFFFFFF
#define MOONLIT_DAWN_EMBER_PRIMARY_CONTAINER LCD_RGBPACK(244, 225, 204)
#define MOONLIT_DAWN_EMBER_PRIMARY_CONTAINER_RGB24 0xF4E1CC
#define MOONLIT_DAWN_EMBER_ON_PRIMARY_CONTAINER LCD_RGBPACK(61, 36, 16)
#define MOONLIT_DAWN_EMBER_ON_PRIMARY_CONTAINER_RGB24 0x3D2410
#define MOONLIT_NIGHT_MOSS_PRIMARY LCD_RGBPACK(184, 212, 143)
#define MOONLIT_NIGHT_MOSS_PRIMARY_RGB24 0xB8D48F
#define MOONLIT_NIGHT_MOSS_ON_PRIMARY LCD_RGBPACK(44, 61, 15)
#define MOONLIT_NIGHT_MOSS_ON_PRIMARY_RGB24 0x2C3D0F
#define MOONLIT_NIGHT_MOSS_PRIMARY_CONTAINER LCD_RGBPACK(62, 82, 28)
#define MOONLIT_NIGHT_MOSS_PRIMARY_CONTAINER_RGB24 0x3E521C
#define MOONLIT_NIGHT_MOSS_ON_PRIMARY_CONTAINER LCD_RGBPACK(227, 240, 201)
#define MOONLIT_NIGHT_MOSS_ON_PRIMARY_CONTAINER_RGB24 0xE3F0C9
#define MOONLIT_DAWN_MOSS_PRIMARY LCD_RGBPACK(90, 110, 44)
#define MOONLIT_DAWN_MOSS_PRIMARY_RGB24 0x5A6E2C
#define MOONLIT_DAWN_MOSS_ON_PRIMARY LCD_RGBPACK(255, 255, 255)
#define MOONLIT_DAWN_MOSS_ON_PRIMARY_RGB24 0xFFFFFF
#define MOONLIT_DAWN_MOSS_PRIMARY_CONTAINER LCD_RGBPACK(231, 240, 206)
#define MOONLIT_DAWN_MOSS_PRIMARY_CONTAINER_RGB24 0xE7F0CE
#define MOONLIT_DAWN_MOSS_ON_PRIMARY_CONTAINER LCD_RGBPACK(42, 54, 16)
#define MOONLIT_DAWN_MOSS_ON_PRIMARY_CONTAINER_RGB24 0x2A3610

#endif /* MOONLIT_TOKENS_H */
